# Generated by Django 4.1 on 2022-09-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('idAgendamiento', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('horario_a', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('idCondicion', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('indicativo_c', models.CharField(max_length=45)),
                ('condicion_c', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_salud',
            fields=[
                ('idEntidad_salud', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('empresa_es', models.CharField(max_length=45)),
                ('valor_es', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=45)),
                ('sector_productivo', models.CharField(max_length=45)),
                ('fecha_creacion', models.DateTimeField()),
                ('ciudad', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('idOficio', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('oficio_o', models.CharField(max_length=45)),
                ('indicativo_o', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('costo_t', models.CharField(max_length=45)),
                ('fecha_t', models.CharField(max_length=45)),
                ('descripcion_t', models.CharField(max_length=45)),
                ('Entidad_salud_idEntidad_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.entidad_salud')),
                ('Oficio_idOficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.oficio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_Usuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombres_u', models.CharField(max_length=45)),
                ('apellidos_u', models.CharField(max_length=45)),
                ('documento_u', models.CharField(max_length=45, unique=True)),
                ('email_u', models.EmailField(max_length=254, unique=True)),
                ('telefono_u', models.CharField(max_length=45)),
                ('direccion_u', models.CharField(max_length=45)),
                ('nombre_r', models.CharField(max_length=45)),
                ('telefono_r', models.CharField(max_length=45)),
                ('parentesco_r', models.CharField(max_length=45)),
                ('documento_r', models.CharField(max_length=45)),
                ('usuario_u', models.CharField(max_length=45, unique=True)),
                ('password_u', models.CharField(max_length=45)),
                ('Condicion_idCondicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.condicion')),
                ('Entidad_salud_idEntidad_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.entidad_salud')),
                ('Transaccion_idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idEmpleados', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombres_e', models.CharField(max_length=45)),
                ('apellidos_e', models.CharField(max_length=45)),
                ('documento_e', models.CharField(max_length=45, unique=True)),
                ('email_e', models.EmailField(max_length=254, unique=True)),
                ('telefono_e', models.CharField(max_length=45)),
                ('direccion_e', models.CharField(max_length=45)),
                ('tFecha_creacion', models.CharField(max_length=45)),
                ('Agendamiento_ideAgendamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.agendamiento')),
                ('Condicion_idCondicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.condicion')),
                ('Oficio_idOficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.oficio')),
            ],
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='Transaccion_idTransaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.transaccion'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='Usuarios_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.usuarios'),
        ),
    ]
