# Generated by Django 4.1 on 2022-10-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIPS', '0005_rename_entidad_salud_identidad_salud_transaccion_identidad_salud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='ideAgendamiento',
            new_name='idAgendamiento',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='idEntidad_salud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.entidad_salud'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='idOficio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.oficio'),
        ),
    ]
