# Generated by Django 4.1 on 2022-10-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIPS', '0006_rename_ideagendamiento_empleados_idagendamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='idEntidad_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.entidad_salud'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='idOficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionIPS.oficio'),
        ),
    ]
