# Generated by Django 4.1 on 2022-09-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIPS', '0002_agendamiento_fecha_condicion_fecha_empleados_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='tFecha_creacion',
        ),
        migrations.RemoveField(
            model_name='entidad_salud',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_t',
        ),
    ]
