# Generated by Django 4.1 on 2022-09-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIPS', '0003_remove_empleados_tfecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamiento',
            old_name='Transaccion_idTransaccion',
            new_name='idTransaccion',
        ),
        migrations.RenameField(
            model_name='agendamiento',
            old_name='Usuarios_idUsuario',
            new_name='id_Usuario',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='Condicion_idCondicion',
            new_name='idCondicion',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='Oficio_idOficio',
            new_name='idOficio',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='Agendamiento_ideAgendamiento',
            new_name='ideAgendamiento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Condicion_idCondicion',
            new_name='idCondicion',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Entidad_salud_idEntidad_salud',
            new_name='idEntidad_salud',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Transaccion_idTransaccion',
            new_name='idTransaccion',
        ),
    ]
