# Generated by Django 4.1 on 2022-09-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIPS', '0004_rename_transaccion_idtransaccion_agendamiento_idtransaccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='Entidad_salud_idEntidad_salud',
            new_name='idEntidad_salud',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='Oficio_idOficio',
            new_name='idOficio',
        ),
    ]
